baseURL = "https://d36.ch/"
disqusShortname = ""
googleAnalytics = "G-1MSQGC8M1F"
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "D36.ch - digitally productive"
[markup.goldmark.renderer]
unsafe = true
