######################## default configuration ####################
baseURL = "http://examplesite.org/"
title = "D36.ch"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "G-1MSQGC8M1F" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true