baseURL = "http://examplesite.org/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "D36.ch - digitally productive"
[markup.goldmark.renderer]
unsafe = true
