############################# English ############################
[en]
languageName = "En"
title = "D36.ch - Tech Solutions for Digital Transformation in Healthcare"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "About Us"
footer_menu_middle = "Verticals"
footer_menu_right = "Expertise"
footer_content = "We provide Swiss enterprises and SME’s with digital solutions across multiple technologies combined with consulting services."
# copyright
copyright = "2021 D36.ch Sàrl | [Privacy Policy](https://d36.intellias.healthcare/privacy-policy/) | [Cookie Policy](https://d36.intellias.healthcare/cookie-policy/)"



############################# Deutsch ############################
[de]
languageName = "De"
title = "Bigspring Hugo"
contentDir = "content/deutsch" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"