# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Insights"
url = "insights"
weight = 4

[[main]]
name = "Verticals"
url = "verticals"
weight = 2

[[main]]
name = "Technologies & Services"
url = "technologies"
weight = 3

[[main]]
name = "Careers"
url = "careers"
weight = 5

# footer menu left
[[footer_left]]
name = "Our Team"
url = "team"

[[footer_left]]
name = "Our Strategy"
url = "strategy"

[[footer_left]]
name = "Our Approach"
url = "approach"


# footer menu middle
[[footer_middle]]
name = "Digital Health"
url = "digital-health"

[[footer_middle]]
name = "Industry 4.0"
url = "industry4.0"

[[footer_middle]]
name = "AgroTech"
url = "agrotech"

# footer menu right
[[footer_right]]
name = "Platforms"
url = "platforms"

[[footer_right]]
name = "Data Science"
url = "datascience"

[[footer_right]]
name = "DevOps as a Service"
url = "devops"

[[footer_right]]
name = "Partners"
url = "partners"